[tool.poetry]
name = "pyfinra"
version = "0.1.2"
description = ""
authors = ["SÃ¶ren Michaels <soeren.michaels@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.25.1"
pandas = "^1.2.3"
finsymbols = "^1.3.0"
selenium = "^3.141.0"
pytest = "^6.2.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
